[workspace]
channels = ["https://prefix.dev/conda-forge"]
name = "pytorch-conda-forge"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.4.1,<3"
matplotlib = ">=3.10.8,<4"
pytorch-gpu = "*"
pip = ">=25.3,<26"
ipykernel = ">=7.1.0,<8"
uproot = ">=5.6.9,<6"
click = ">=8.3.1,<9"
structlog = ">=24.4.0,<25"

[system-requirements]
cuda = "12.6"
